AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for React frontend + API + DynamoDB + 6 Lambdas

Resources:
  # API Gateway Rest API (SAM will auto-create it)
  RollWithIt: 
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: RollWithIt

  # Lambda functions (6 total)
  createPackingList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createPackingList
      Handler: createPackingList/index.handler
      Runtime: nodejs22.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      CodeUri: ./src
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref RollWithIt
            Path: /createPackingList
            Method: post

  addToPackingList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: addToPackingList
      Handler: addToPackingList/index.handler
      Runtime: nodejs22.x
      CodeUri: ./src
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref RollWithIt
            Path: /addToPackingList
            Method: post

  getAllPackingLists:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getAllPackingLists
      Handler: getAllPackingLists/index.handler
      Runtime: nodejs22.x
      CodeUri: ./src
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref RollWithIt
            Path: /getAllPackingLists
            Method: get

  getPackingList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getPackingList
      Handler: getPackingList/index.handler
      Runtime: nodejs22.x
      CodeUri: ./src
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref RollWithIt
            Path: /getPackingList
            Method: get

  updatePackingList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updatePackingList
      Handler: updatePackingList/index.handler
      Runtime: nodejs22.x
      CodeUri: ./src
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /updatePackingList
            Method: post
            ApiId: !Ref RollWithIt

  updatePackingListItem:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updatePackingListItem
      Handler: updatePackingListItem/index.handler
      Runtime: nodejs22.x
      CodeUri: ./src
      Policies:
        - DynamoDBCrudPolicy:
            TableName: roll_with_it
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref RollWithIt
            Path: /updatePackingListItem
            Method: post

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint base URL"
    Value: !Sub "https://${RollWithIt}.execute-api.${AWS::Region}.amazonaws.com"